victoire_widget_poll:
    radio:
        answer:
            entity: Victoire\Widget\PollBundle\Entity\Answer\RadioAnswer
            form: Victoire\Widget\PollBundle\Form\Answer\RadioAnswerType
            template: radio
        question:
            entity: Victoire\Widget\PollBundle\Entity\Question\Radio
            form: Victoire\Widget\PollBundle\Form\Question\QuestionRadioType
            template: radio
    image:
        answer:
            entity: Victoire\Widget\PollBundle\Entity\Answer\ImageAnswer
            form: Victoire\Widget\PollBundle\Form\Answer\ImageAnswerType
            template: image
        question:
            entity: Victoire\Widget\PollBundle\Entity\Question\ImageChooser
            form: Victoire\Widget\PollBundle\Form\Question\ImageChooserType
            template: image